### ISSUE TITLE
How to distinguish Different exception？

### ISSUE THREAD

**Issue by pengzechen** [arceos-hypervisor/arm_vcpu#6]
How to distinguish different exceptions with vmexit_aarch64_handler？

**Comment by pengzechen** [comment]
```vmexit_handler``` only handle sync exceptions, how do we handle irqs ?

**Comment by pengzechen** [comment]
If you mimic the x86 "vmexit," an IRQ arrival would also count as a vmexit, wouldn't it?

**Comment by pengzechen** [comment]
![image](https://github.com/user-attachments/assets/9ca93920-a55e-43b0-b285-ab402e7e5aef)
Can this work?

**Comment by hky1999** [comment]
> ![image](https://private-user-images.githubusercontent.com/87976177/361181252-9ca93920-a55e-43b0-b285-ab402e7e5aef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDI0NjIsIm5iZiI6MTcyNDY0MjE2MiwicGF0aCI6Ii84Nzk3NjE3Ny8zNjExODEyNTItOWNhOTM5MjAtYTU1ZS00M2IwLWIyODUtYWI0MDJlN2U1YWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAzMTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMTY3OTk1OWJiZjc5Y2ZjOGYxNDlmNmMzMGYzOWFlMDFmZTUwNWNhZDUyY2UxNzc2NTc0NjRmODFhYTdlMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPm7BV7Yah3rSXVW_8YBqFnPZ_rGTnNFBx7dfhha3jI) Can this work?

Yes, and I think you can modify `run_guest` to something like
```Rust
 #[inline(never)]
    fn run_guest(&mut self) -> usize {
        unsafe {
            core::arch::asm!(
                save_regs_to_stack!(),  // save host context
                "mov x9, sp",
                "mov x10, {0}",
                "str x9, [x10]",    // save host stack top in the vcpu struct
                "mov x0, {0}",
                "b context_vm_entry",
                in(reg) &self.host_stack_top as *const _ as usize,
                options(nostack)
            );
        }
    }
```
Remember that ARM use `x0` register to store the return value, you may need to modify some Rust inline assembly to ensure the return value is correct.

Also, you need to simplify the `save_regs_to_stack` and `restore_regs_from_stack` macro, since `run_guest` is just a function call and we only need to maintain the "callee saved registers". 

Such semantic can refer to [task context switch design](https://github.com/arceos-org/arceos/blob/6f98bc411e4c799085739ebb9ef4de28de4e7f30/modules/axhal/src/arch/aarch64/context.rs#L96) in ArceOS, since `switch_to()` is alse a function call.
